Improve DOI script.

diff --git a/registry-doi/generate-doi-for-old-download b/registry-doi/generate-doi-for-old-download
--- a/registry-doi/generate-doi-for-old-download
+++ b/registry-doi/generate-doi-for-old-download
@@ -35,13 +35,20 @@ date=$(curl -Ss https://api.gbif.org/v1/occurrence/download/$downloadKey | jq -r
 
         title=$(curl -Ss https://api.gbif.org/v1/dataset/$datasetKey | jq -r .title)
         doi=$(curl -Ss https://api.gbif.org/v1/dataset/$datasetKey | jq -r .doi)
-        citation=$(curl -Ss https://api.gbif.org/v1/dataset/$datasetKey | jq -r .citation.text | sed s/$today.$/$date./)
+
+        if [[ $doi = 'null' ]]; then
+            echo >&2 "Dataset $datasetKey ($title) does not have a DOI, attempting to assign one."
+            ./generate-doi-for-old-dataset $datasetKey >&2
+            doi=$(curl -Ss https://api.gbif.org/v1/dataset/$datasetKey | jq -r .doi)
+        fi
 
         if [[ $doi = 'null' ]]; then
             echo "ROLLBACK;"
-            echo >&2 "Dataset $datasetKey ($title) does not have a DOI, first assign one."
+            echo >&2 "Dataset $datasetKey ($title) does not have a DOI, and assignment failed."
             exit 1
         fi
+
+        citation=$(curl -Ss https://api.gbif.org/v1/dataset/$datasetKey | jq -r .citation.text | sed s/$today.$/$date./)
 
         echo "UPDATE dataset_occurrence_download SET dataset_title = (\$\$$title\$\$), dataset_doi = '$doi', dataset_citation = (\$\$$citation\$\$) WHERE download_key = '$downloadKey' AND dataset_key = '$datasetKey' AND dataset_title IS NULL AND dataset_doi IS NULL AND dataset_citation IS NULL;"
 
